// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2014.4
// Copyright (C) 2014 Xilinx Inc. All rights reserved.
// 
// ===========================================================

#ifndef _xillybus_wrapper_HH_
#define _xillybus_wrapper_HH_

#include "systemc.h"
#include "AESL_pkg.h"

#include "xillybus_wrapper_xilly_decprint.h"
#include "xillybus_wrapper_xilly_puts_1.h"
#include "xillybus_wrapper_p_str3.h"
#include "xillybus_wrapper_p_str4.h"
#include "xillybus_wrapper_p_str5.h"
#include "xillybus_wrapper_p_str6.h"
#include "xillybus_wrapper_p_str7.h"

namespace ap_rtl {

struct xillybus_wrapper : public sc_module {
    // Port declarations 11
    sc_in_clk ap_clk;
    sc_in< sc_logic > ap_rst;
    sc_in< sc_lv<32> > in_r_dout;
    sc_in< sc_logic > in_r_empty_n;
    sc_out< sc_logic > in_r_read;
    sc_out< sc_lv<32> > out_r_din;
    sc_in< sc_logic > out_r_full_n;
    sc_out< sc_logic > out_r_write;
    sc_in< sc_lv<8> > debug_ready;
    sc_out< sc_lv<8> > debug_out;
    sc_out< sc_logic > debug_out_ap_vld;


    // Module declarations
    xillybus_wrapper(sc_module_name name);
    SC_HAS_PROCESS(xillybus_wrapper);

    ~xillybus_wrapper();

    sc_trace_file* mVcdFile;

    ofstream mHdltvinHandle;
    ofstream mHdltvoutHandle;
    xillybus_wrapper_p_str3* p_str3_U;
    xillybus_wrapper_p_str4* p_str4_U;
    xillybus_wrapper_p_str5* p_str5_U;
    xillybus_wrapper_p_str6* p_str6_U;
    xillybus_wrapper_p_str7* p_str7_U;
    xillybus_wrapper_xilly_decprint* grp_xillybus_wrapper_xilly_decprint_fu_172;
    xillybus_wrapper_xilly_puts_1* grp_xillybus_wrapper_xilly_puts_1_fu_183;
    sc_signal< sc_lv<4> > p_str3_address0;
    sc_signal< sc_logic > p_str3_ce0;
    sc_signal< sc_lv<7> > p_str3_q0;
    sc_signal< sc_lv<2> > p_str4_address0;
    sc_signal< sc_logic > p_str4_ce0;
    sc_signal< sc_lv<7> > p_str4_q0;
    sc_signal< sc_lv<2> > p_str5_address0;
    sc_signal< sc_logic > p_str5_ce0;
    sc_signal< sc_lv<8> > p_str5_q0;
    sc_signal< sc_lv<2> > p_str6_address0;
    sc_signal< sc_logic > p_str6_ce0;
    sc_signal< sc_lv<8> > p_str6_q0;
    sc_signal< sc_lv<1> > p_str7_address0;
    sc_signal< sc_logic > p_str7_ce0;
    sc_signal< sc_lv<4> > p_str7_q0;
    sc_signal< sc_lv<20> > ap_CS_fsm;
    sc_signal< sc_logic > ap_sig_cseq_ST_st2_fsm_1;
    sc_signal< bool > ap_sig_bdd_83;
    sc_signal< sc_lv<1> > tmp_i_fu_203_p2;
    sc_signal< sc_lv<1> > tmp_i_reg_354;
    sc_signal< sc_lv<4> > p_rec_i_fu_209_p2;
    sc_signal< sc_lv<4> > p_rec_i_reg_358;
    sc_signal< sc_lv<8> > p_str3_load_cast_fu_215_p1;
    sc_signal< sc_lv<8> > p_str3_load_cast_reg_363;
    sc_signal< sc_logic > ap_sig_cseq_ST_st3_fsm_2;
    sc_signal< bool > ap_sig_bdd_97;
    sc_signal< bool > ap_sig_bdd_104;
    sc_signal< sc_lv<8> > b_fu_219_p1;
    sc_signal< sc_lv<8> > b_reg_368;
    sc_signal< sc_lv<8> > r_fu_223_p4;
    sc_signal< sc_lv<8> > r_reg_373;
    sc_signal< sc_lv<10> > r_cast6_fu_233_p1;
    sc_signal< sc_lv<10> > r_cast6_reg_378;
    sc_signal< sc_lv<8> > g_fu_237_p4;
    sc_signal< sc_lv<8> > g_reg_383;
    sc_signal< sc_lv<9> > g_cast5_fu_247_p1;
    sc_signal< sc_lv<9> > g_cast5_reg_388;
    sc_signal< sc_lv<9> > b_cast4_fu_251_p1;
    sc_signal< sc_lv<9> > b_cast4_reg_393;
    sc_signal< sc_logic > ap_sig_cseq_ST_st5_fsm_4;
    sc_signal< bool > ap_sig_bdd_127;
    sc_signal< sc_lv<1> > tmp_i2_fu_269_p2;
    sc_signal< sc_lv<1> > tmp_i2_reg_406;
    sc_signal< sc_lv<2> > p_rec_i7_fu_275_p2;
    sc_signal< sc_lv<2> > p_rec_i7_reg_410;
    sc_signal< sc_lv<8> > p_str4_load_cast_fu_281_p1;
    sc_signal< sc_lv<8> > p_str4_load_cast_reg_415;
    sc_signal< sc_logic > ap_sig_cseq_ST_st6_fsm_5;
    sc_signal< bool > ap_sig_bdd_140;
    sc_signal< sc_logic > ap_sig_cseq_ST_st17_fsm_16;
    sc_signal< bool > ap_sig_bdd_149;
    sc_signal< sc_lv<8> > p_str7_load_cast_fu_299_p1;
    sc_signal< sc_lv<8> > p_str7_load_cast_reg_428;
    sc_signal< sc_logic > ap_sig_cseq_ST_st18_fsm_17;
    sc_signal< bool > ap_sig_bdd_158;
    sc_signal< sc_lv<10> > y_reg_433;
    sc_signal< sc_lv<1> > p_0_rec_i8_reg_157;
    sc_signal< sc_logic > grp_xillybus_wrapper_xilly_decprint_fu_172_ap_start;
    sc_signal< sc_logic > grp_xillybus_wrapper_xilly_decprint_fu_172_ap_done;
    sc_signal< sc_logic > grp_xillybus_wrapper_xilly_decprint_fu_172_ap_idle;
    sc_signal< sc_logic > grp_xillybus_wrapper_xilly_decprint_fu_172_ap_ready;
    sc_signal< sc_lv<8> > grp_xillybus_wrapper_xilly_decprint_fu_172_val_r;
    sc_signal< sc_lv<8> > grp_xillybus_wrapper_xilly_decprint_fu_172_debug_ready;
    sc_signal< sc_lv<8> > grp_xillybus_wrapper_xilly_decprint_fu_172_debug_out;
    sc_signal< sc_logic > grp_xillybus_wrapper_xilly_decprint_fu_172_debug_out_ap_vld;
    sc_signal< sc_logic > grp_xillybus_wrapper_xilly_puts_1_fu_183_ap_start;
    sc_signal< sc_logic > grp_xillybus_wrapper_xilly_puts_1_fu_183_ap_done;
    sc_signal< sc_logic > grp_xillybus_wrapper_xilly_puts_1_fu_183_ap_idle;
    sc_signal< sc_logic > grp_xillybus_wrapper_xilly_puts_1_fu_183_ap_ready;
    sc_signal< sc_lv<2> > grp_xillybus_wrapper_xilly_puts_1_fu_183_str_address0;
    sc_signal< sc_logic > grp_xillybus_wrapper_xilly_puts_1_fu_183_str_ce0;
    sc_signal< sc_lv<8> > grp_xillybus_wrapper_xilly_puts_1_fu_183_str_q0;
    sc_signal< sc_lv<8> > grp_xillybus_wrapper_xilly_puts_1_fu_183_debug_ready;
    sc_signal< sc_lv<8> > grp_xillybus_wrapper_xilly_puts_1_fu_183_debug_out;
    sc_signal< sc_logic > grp_xillybus_wrapper_xilly_puts_1_fu_183_debug_out_ap_vld;
    sc_signal< sc_lv<4> > p_0_rec_i_reg_135;
    sc_signal< sc_logic > ap_sig_cseq_ST_st1_fsm_0;
    sc_signal< bool > ap_sig_bdd_196;
    sc_signal< sc_logic > ap_sig_cseq_ST_st4_fsm_3;
    sc_signal< bool > ap_sig_bdd_203;
    sc_signal< sc_lv<1> > tmp_fu_255_p1;
    sc_signal< sc_lv<2> > p_0_rec_i1_reg_146;
    sc_signal< sc_logic > ap_sig_cseq_ST_st7_fsm_6;
    sc_signal< bool > ap_sig_bdd_217;
    sc_signal< sc_lv<1> > tmp_1_fu_285_p1;
    sc_signal< sc_logic > ap_sig_cseq_ST_st16_fsm_15;
    sc_signal< bool > ap_sig_bdd_229;
    sc_signal< sc_logic > ap_sig_cseq_ST_st19_fsm_18;
    sc_signal< bool > ap_sig_bdd_239;
    sc_signal< sc_lv<1> > tmp_2_fu_336_p1;
    sc_signal< sc_logic > grp_xillybus_wrapper_xilly_decprint_fu_172_ap_start_ap_start_reg;
    sc_signal< sc_logic > ap_sig_cseq_ST_st11_fsm_10;
    sc_signal< bool > ap_sig_bdd_255;
    sc_signal< sc_logic > ap_sig_cseq_ST_st15_fsm_14;
    sc_signal< bool > ap_sig_bdd_263;
    sc_signal< sc_logic > ap_sig_cseq_ST_st8_fsm_7;
    sc_signal< bool > ap_sig_bdd_271;
    sc_signal< sc_logic > ap_sig_cseq_ST_st12_fsm_11;
    sc_signal< bool > ap_sig_bdd_278;
    sc_signal< sc_logic > grp_xillybus_wrapper_xilly_puts_1_fu_183_ap_start_ap_start_reg;
    sc_signal< sc_logic > ap_sig_cseq_ST_st9_fsm_8;
    sc_signal< bool > ap_sig_bdd_314;
    sc_signal< sc_logic > ap_sig_cseq_ST_st13_fsm_12;
    sc_signal< bool > ap_sig_bdd_321;
    sc_signal< sc_logic > ap_sig_cseq_ST_st10_fsm_9;
    sc_signal< bool > ap_sig_bdd_329;
    sc_signal< sc_logic > ap_sig_cseq_ST_st14_fsm_13;
    sc_signal< bool > ap_sig_bdd_336;
    sc_signal< sc_lv<32> > p_0_rec_i_cast_fu_198_p1;
    sc_signal< sc_lv<32> > p_0_rec_i1_cast_fu_264_p1;
    sc_signal< sc_lv<32> > p_0_rec_i8_cast_fu_294_p1;
    sc_signal< sc_logic > ap_sig_cseq_ST_st20_fsm_19;
    sc_signal< bool > ap_sig_bdd_361;
    sc_signal< sc_lv<9> > tmp1_fu_303_p2;
    sc_signal< sc_lv<10> > tmp1_cast_fu_307_p1;
    sc_signal< sc_lv<10> > tmp_3_fu_311_p2;
    sc_signal< sc_lv<10> > mul_fu_320_p0;
    sc_signal< sc_lv<22> > mul_fu_320_p2;
    sc_signal< sc_lv<20> > ap_NS_fsm;
    sc_signal< sc_lv<22> > mul_fu_320_p00;
    static const sc_logic ap_const_logic_1;
    static const sc_logic ap_const_logic_0;
    static const sc_lv<20> ap_ST_st1_fsm_0;
    static const sc_lv<20> ap_ST_st2_fsm_1;
    static const sc_lv<20> ap_ST_st3_fsm_2;
    static const sc_lv<20> ap_ST_st4_fsm_3;
    static const sc_lv<20> ap_ST_st5_fsm_4;
    static const sc_lv<20> ap_ST_st6_fsm_5;
    static const sc_lv<20> ap_ST_st7_fsm_6;
    static const sc_lv<20> ap_ST_st8_fsm_7;
    static const sc_lv<20> ap_ST_st9_fsm_8;
    static const sc_lv<20> ap_ST_st10_fsm_9;
    static const sc_lv<20> ap_ST_st11_fsm_10;
    static const sc_lv<20> ap_ST_st12_fsm_11;
    static const sc_lv<20> ap_ST_st13_fsm_12;
    static const sc_lv<20> ap_ST_st14_fsm_13;
    static const sc_lv<20> ap_ST_st15_fsm_14;
    static const sc_lv<20> ap_ST_st16_fsm_15;
    static const sc_lv<20> ap_ST_st17_fsm_16;
    static const sc_lv<20> ap_ST_st18_fsm_17;
    static const sc_lv<20> ap_ST_st19_fsm_18;
    static const sc_lv<20> ap_ST_st20_fsm_19;
    static const sc_lv<32> ap_const_lv32_1;
    static const sc_lv<1> ap_const_lv1_1;
    static const sc_lv<32> ap_const_lv32_2;
    static const sc_lv<1> ap_const_lv1_0;
    static const sc_lv<32> ap_const_lv32_4;
    static const sc_lv<32> ap_const_lv32_5;
    static const sc_lv<32> ap_const_lv32_10;
    static const sc_lv<32> ap_const_lv32_11;
    static const sc_lv<4> ap_const_lv4_0;
    static const sc_lv<32> ap_const_lv32_0;
    static const sc_lv<32> ap_const_lv32_3;
    static const sc_lv<2> ap_const_lv2_0;
    static const sc_lv<32> ap_const_lv32_6;
    static const sc_lv<32> ap_const_lv32_F;
    static const sc_lv<32> ap_const_lv32_12;
    static const sc_lv<32> ap_const_lv32_A;
    static const sc_lv<32> ap_const_lv32_E;
    static const sc_lv<32> ap_const_lv32_7;
    static const sc_lv<32> ap_const_lv32_B;
    static const sc_lv<32> ap_const_lv32_8;
    static const sc_lv<32> ap_const_lv32_C;
    static const sc_lv<32> ap_const_lv32_9;
    static const sc_lv<32> ap_const_lv32_D;
    static const sc_lv<32> ap_const_lv32_13;
    static const sc_lv<4> ap_const_lv4_F;
    static const sc_lv<4> ap_const_lv4_1;
    static const sc_lv<32> ap_const_lv32_17;
    static const sc_lv<2> ap_const_lv2_2;
    static const sc_lv<2> ap_const_lv2_1;
    static const sc_lv<22> ap_const_lv22_556;
    static const sc_lv<32> ap_const_lv32_15;
    // Thread declarations
    void thread_ap_clk_no_reset_();
    void thread_ap_sig_bdd_104();
    void thread_ap_sig_bdd_127();
    void thread_ap_sig_bdd_140();
    void thread_ap_sig_bdd_149();
    void thread_ap_sig_bdd_158();
    void thread_ap_sig_bdd_196();
    void thread_ap_sig_bdd_203();
    void thread_ap_sig_bdd_217();
    void thread_ap_sig_bdd_229();
    void thread_ap_sig_bdd_239();
    void thread_ap_sig_bdd_255();
    void thread_ap_sig_bdd_263();
    void thread_ap_sig_bdd_271();
    void thread_ap_sig_bdd_278();
    void thread_ap_sig_bdd_314();
    void thread_ap_sig_bdd_321();
    void thread_ap_sig_bdd_329();
    void thread_ap_sig_bdd_336();
    void thread_ap_sig_bdd_361();
    void thread_ap_sig_bdd_83();
    void thread_ap_sig_bdd_97();
    void thread_ap_sig_cseq_ST_st10_fsm_9();
    void thread_ap_sig_cseq_ST_st11_fsm_10();
    void thread_ap_sig_cseq_ST_st12_fsm_11();
    void thread_ap_sig_cseq_ST_st13_fsm_12();
    void thread_ap_sig_cseq_ST_st14_fsm_13();
    void thread_ap_sig_cseq_ST_st15_fsm_14();
    void thread_ap_sig_cseq_ST_st16_fsm_15();
    void thread_ap_sig_cseq_ST_st17_fsm_16();
    void thread_ap_sig_cseq_ST_st18_fsm_17();
    void thread_ap_sig_cseq_ST_st19_fsm_18();
    void thread_ap_sig_cseq_ST_st1_fsm_0();
    void thread_ap_sig_cseq_ST_st20_fsm_19();
    void thread_ap_sig_cseq_ST_st2_fsm_1();
    void thread_ap_sig_cseq_ST_st3_fsm_2();
    void thread_ap_sig_cseq_ST_st4_fsm_3();
    void thread_ap_sig_cseq_ST_st5_fsm_4();
    void thread_ap_sig_cseq_ST_st6_fsm_5();
    void thread_ap_sig_cseq_ST_st7_fsm_6();
    void thread_ap_sig_cseq_ST_st8_fsm_7();
    void thread_ap_sig_cseq_ST_st9_fsm_8();
    void thread_b_cast4_fu_251_p1();
    void thread_b_fu_219_p1();
    void thread_debug_out();
    void thread_debug_out_ap_vld();
    void thread_g_cast5_fu_247_p1();
    void thread_g_fu_237_p4();
    void thread_grp_xillybus_wrapper_xilly_decprint_fu_172_ap_start();
    void thread_grp_xillybus_wrapper_xilly_decprint_fu_172_debug_ready();
    void thread_grp_xillybus_wrapper_xilly_decprint_fu_172_val_r();
    void thread_grp_xillybus_wrapper_xilly_puts_1_fu_183_ap_start();
    void thread_grp_xillybus_wrapper_xilly_puts_1_fu_183_debug_ready();
    void thread_grp_xillybus_wrapper_xilly_puts_1_fu_183_str_q0();
    void thread_in_r_read();
    void thread_mul_fu_320_p0();
    void thread_mul_fu_320_p00();
    void thread_mul_fu_320_p2();
    void thread_out_r_din();
    void thread_out_r_write();
    void thread_p_0_rec_i1_cast_fu_264_p1();
    void thread_p_0_rec_i8_cast_fu_294_p1();
    void thread_p_0_rec_i_cast_fu_198_p1();
    void thread_p_rec_i7_fu_275_p2();
    void thread_p_rec_i_fu_209_p2();
    void thread_p_str3_address0();
    void thread_p_str3_ce0();
    void thread_p_str3_load_cast_fu_215_p1();
    void thread_p_str4_address0();
    void thread_p_str4_ce0();
    void thread_p_str4_load_cast_fu_281_p1();
    void thread_p_str5_address0();
    void thread_p_str5_ce0();
    void thread_p_str6_address0();
    void thread_p_str6_ce0();
    void thread_p_str7_address0();
    void thread_p_str7_ce0();
    void thread_p_str7_load_cast_fu_299_p1();
    void thread_r_cast6_fu_233_p1();
    void thread_r_fu_223_p4();
    void thread_tmp1_cast_fu_307_p1();
    void thread_tmp1_fu_303_p2();
    void thread_tmp_1_fu_285_p1();
    void thread_tmp_2_fu_336_p1();
    void thread_tmp_3_fu_311_p2();
    void thread_tmp_fu_255_p1();
    void thread_tmp_i2_fu_269_p2();
    void thread_tmp_i_fu_203_p2();
    void thread_ap_NS_fsm();
    void thread_hdltv_gen();
};

}

using namespace ap_rtl;

#endif
