#pragma line 1 "coprocess/example/src/main.c" ::: -10
#pragma line 1 "coprocess/example/src/main.c" 1 ::: -9
#pragma line 1 "<built-in>" 1 ::: -8
#pragma line 1 "<built-in>" 3 ::: -7
#pragma line 148 "<built-in>" 3 ::: -6
#pragma line 1 "<command line>" 1 ::: -5
#pragma line 1 "C:/Xilinx/Vivado_HLS/2014.4/common/technology/autopilot\\etc/autopilot_ssdm_op.h" 1 ::: 3
#pragma line 278 "C:/Xilinx/Vivado_HLS/2014.4/common/technology/autopilot\\etc/autopilot_ssdm_op.h" ::: 56
#pragma line 9 "<command line>" 2 ::: 182
#pragma line 1 "<built-in>" 2 ::: 183
#pragma line 1 "coprocess/example/src/main.c" 2 ::: 184
#pragma line 1 "C:/Xilinx/Vivado_HLS/2014.4/win32/tools/clang/bin/../lib/clang/3.1/../../../include\\math.h" 1 3 ::: 185
#pragma line 16 "C:/Xilinx/Vivado_HLS/2014.4/win32/tools/clang/bin/../lib/clang/3.1/../../../include\\math.h" 3 ::: 202
#pragma line 1 "C:/Xilinx/Vivado_HLS/2014.4/win32/tools/clang/bin/../lib/clang/3.1/../../../include\\_mingw.h" 1 3 ::: 207
#pragma line 32 "C:/Xilinx/Vivado_HLS/2014.4/win32/tools/clang/bin/../lib/clang/3.1/../../../include\\_mingw.h" 3 ::: 230
#pragma line 32 "C:/Xilinx/Vivado_HLS/2014.4/win32/tools/clang/bin/../lib/clang/3.1/../../../include\\_mingw.h" 3 ::: 231
#pragma line 122 "C:/Xilinx/Vivado_HLS/2014.4/win32/tools/clang/bin/../lib/clang/3.1/../../../include\\_mingw.h" 3 ::: 278
#pragma line 141 "C:/Xilinx/Vivado_HLS/2014.4/win32/tools/clang/bin/../lib/clang/3.1/../../../include\\_mingw.h" 3 ::: 281
#pragma line 231 "C:/Xilinx/Vivado_HLS/2014.4/win32/tools/clang/bin/../lib/clang/3.1/../../../include\\_mingw.h" 3 ::: 287
#pragma line 253 "C:/Xilinx/Vivado_HLS/2014.4/win32/tools/clang/bin/../lib/clang/3.1/../../../include\\_mingw.h" 3 ::: 291
#pragma line 278 "C:/Xilinx/Vivado_HLS/2014.4/win32/tools/clang/bin/../lib/clang/3.1/../../../include\\_mingw.h" 3 ::: 306
#pragma line 20 "C:/Xilinx/Vivado_HLS/2014.4/win32/tools/clang/bin/../lib/clang/3.1/../../../include\\math.h" 2 3 ::: 310
#pragma line 32 "C:/Xilinx/Vivado_HLS/2014.4/win32/tools/clang/bin/../lib/clang/3.1/../../../include\\math.h" 3 ::: 315
#pragma line 50 "C:/Xilinx/Vivado_HLS/2014.4/win32/tools/clang/bin/../lib/clang/3.1/../../../include\\math.h" 3 ::: 319
#pragma line 67 "C:/Xilinx/Vivado_HLS/2014.4/win32/tools/clang/bin/../lib/clang/3.1/../../../include\\math.h" 3 ::: 321
#pragma line 92 "C:/Xilinx/Vivado_HLS/2014.4/win32/tools/clang/bin/../lib/clang/3.1/../../../include\\math.h" 3 ::: 328
#pragma line 133 "C:/Xilinx/Vivado_HLS/2014.4/win32/tools/clang/bin/../lib/clang/3.1/../../../include\\math.h" 3 ::: 339
#pragma line 195 "C:/Xilinx/Vivado_HLS/2014.4/win32/tools/clang/bin/../lib/clang/3.1/../../../include\\math.h" 3 ::: 383
#pragma line 206 "C:/Xilinx/Vivado_HLS/2014.4/win32/tools/clang/bin/../lib/clang/3.1/../../../include\\math.h" 3 ::: 386
#pragma line 285 "C:/Xilinx/Vivado_HLS/2014.4/win32/tools/clang/bin/../lib/clang/3.1/../../../include\\math.h" 3 ::: 452
#pragma line 313 "C:/Xilinx/Vivado_HLS/2014.4/win32/tools/clang/bin/../lib/clang/3.1/../../../include\\math.h" 3 ::: 454
#pragma line 331 "C:/Xilinx/Vivado_HLS/2014.4/win32/tools/clang/bin/../lib/clang/3.1/../../../include\\math.h" 3 ::: 461
#pragma line 369 "C:/Xilinx/Vivado_HLS/2014.4/win32/tools/clang/bin/../lib/clang/3.1/../../../include\\math.h" 3 ::: 487
#pragma line 414 "C:/Xilinx/Vivado_HLS/2014.4/win32/tools/clang/bin/../lib/clang/3.1/../../../include\\math.h" 3 ::: 500
#pragma line 445 "C:/Xilinx/Vivado_HLS/2014.4/win32/tools/clang/bin/../lib/clang/3.1/../../../include\\math.h" 3 ::: 508
#pragma line 601 "C:/Xilinx/Vivado_HLS/2014.4/win32/tools/clang/bin/../lib/clang/3.1/../../../include\\math.h" 3 ::: 637
#pragma line 768 "C:/Xilinx/Vivado_HLS/2014.4/win32/tools/clang/bin/../lib/clang/3.1/../../../include\\math.h" 3 ::: 732
#pragma line 2 "coprocess/example/src/main.c" 2 ::: 830
#pragma line 1 "C:/Xilinx/Vivado_HLS/2014.4/win32/tools/clang/bin/../lib/clang/3.1/include\\stdint.h" 1 3 4 ::: 831
#pragma line 1 "C:/Xilinx/Vivado_HLS/2014.4/win32/tools/clang/bin/../lib/clang/3.1/../../../include\\stdint.h" 1 3 4 ::: 865
#pragma line 1 "C:/Xilinx/Vivado_HLS/2014.4/win32/tools/clang/bin/../lib/clang/3.1/include\\stddef.h" 1 3 4 ::: 890
#pragma line 56 "C:/Xilinx/Vivado_HLS/2014.4/win32/tools/clang/bin/../lib/clang/3.1/include\\stddef.h" 3 4 ::: 931
#pragma line 25 "C:/Xilinx/Vivado_HLS/2014.4/win32/tools/clang/bin/../lib/clang/3.1/../../../include\\stdint.h" 2 3 4 ::: 938
#pragma line 75 "C:/Xilinx/Vivado_HLS/2014.4/win32/tools/clang/bin/../lib/clang/3.1/../../../include\\stdint.h" 3 4 ::: 981
#pragma line 102 "C:/Xilinx/Vivado_HLS/2014.4/win32/tools/clang/bin/../lib/clang/3.1/../../../include\\stdint.h" 3 4 ::: 994
#pragma line 118 "C:/Xilinx/Vivado_HLS/2014.4/win32/tools/clang/bin/../lib/clang/3.1/../../../include\\stdint.h" 3 4 ::: 996
#pragma line 134 "C:/Xilinx/Vivado_HLS/2014.4/win32/tools/clang/bin/../lib/clang/3.1/../../../include\\stdint.h" 3 4 ::: 998
#pragma line 146 "C:/Xilinx/Vivado_HLS/2014.4/win32/tools/clang/bin/../lib/clang/3.1/../../../include\\stdint.h" 3 4 ::: 1001
#pragma line 165 "C:/Xilinx/Vivado_HLS/2014.4/win32/tools/clang/bin/../lib/clang/3.1/../../../include\\stdint.h" 3 4 ::: 1008
#pragma line 200 "C:/Xilinx/Vivado_HLS/2014.4/win32/tools/clang/bin/../lib/clang/3.1/../../../include\\stdint.h" 3 4 ::: 1033
#pragma line 33 "C:/Xilinx/Vivado_HLS/2014.4/win32/tools/clang/bin/../lib/clang/3.1/include\\stdint.h" 2 3 4 ::: 1035
#pragma line 3 "coprocess/example/src/main.c" 2 ::: 1036
#pragma line 1 "coprocess/example/src/xilly_debug.h" 1 ::: 1037
#pragma line 4 "coprocess/example/src/main.c" 2 ::: 1046
