#pragma line 1 "coprocess/example/src/main.c" ::: 0
#pragma line 1 "coprocess/example/src/main.c" 1 ::: 1
#pragma line 1 "<built-in>" 1 ::: 2
#pragma line 1 "<built-in>" 3 ::: 3
#pragma line 148 "<built-in>" 3 ::: 4
#pragma line 1 "<command line>" 1 ::: 5
#pragma line 1 "C:/Xilinx/Vivado_HLS/2014.4/common/technology/autopilot\\etc/autopilot_ssdm_op.h" 1 ::: 13
#pragma line 278 "C:/Xilinx/Vivado_HLS/2014.4/common/technology/autopilot\\etc/autopilot_ssdm_op.h" ::: 66
#pragma line 9 "<command line>" 2 ::: 192
#pragma line 1 "<built-in>" 2 ::: 193
#pragma line 1 "coprocess/example/src/main.c" 2 ::: 194
#pragma line 1 "C:/Xilinx/Vivado_HLS/2014.4/win32/tools/clang/bin/../lib/clang/3.1/../../../include\\math.h" 1 3 ::: 195
#pragma line 16 "C:/Xilinx/Vivado_HLS/2014.4/win32/tools/clang/bin/../lib/clang/3.1/../../../include\\math.h" 3 ::: 212
#pragma line 1 "C:/Xilinx/Vivado_HLS/2014.4/win32/tools/clang/bin/../lib/clang/3.1/../../../include\\_mingw.h" 1 3 ::: 217
#pragma line 32 "C:/Xilinx/Vivado_HLS/2014.4/win32/tools/clang/bin/../lib/clang/3.1/../../../include\\_mingw.h" 3 ::: 240
#pragma line 32 "C:/Xilinx/Vivado_HLS/2014.4/win32/tools/clang/bin/../lib/clang/3.1/../../../include\\_mingw.h" 3 ::: 241
#pragma line 122 "C:/Xilinx/Vivado_HLS/2014.4/win32/tools/clang/bin/../lib/clang/3.1/../../../include\\_mingw.h" 3 ::: 288
#pragma line 141 "C:/Xilinx/Vivado_HLS/2014.4/win32/tools/clang/bin/../lib/clang/3.1/../../../include\\_mingw.h" 3 ::: 291
#pragma line 231 "C:/Xilinx/Vivado_HLS/2014.4/win32/tools/clang/bin/../lib/clang/3.1/../../../include\\_mingw.h" 3 ::: 297
#pragma line 253 "C:/Xilinx/Vivado_HLS/2014.4/win32/tools/clang/bin/../lib/clang/3.1/../../../include\\_mingw.h" 3 ::: 301
#pragma line 278 "C:/Xilinx/Vivado_HLS/2014.4/win32/tools/clang/bin/../lib/clang/3.1/../../../include\\_mingw.h" 3 ::: 316
#pragma line 20 "C:/Xilinx/Vivado_HLS/2014.4/win32/tools/clang/bin/../lib/clang/3.1/../../../include\\math.h" 2 3 ::: 320
#pragma line 32 "C:/Xilinx/Vivado_HLS/2014.4/win32/tools/clang/bin/../lib/clang/3.1/../../../include\\math.h" 3 ::: 325
#pragma line 50 "C:/Xilinx/Vivado_HLS/2014.4/win32/tools/clang/bin/../lib/clang/3.1/../../../include\\math.h" 3 ::: 329
#pragma line 67 "C:/Xilinx/Vivado_HLS/2014.4/win32/tools/clang/bin/../lib/clang/3.1/../../../include\\math.h" 3 ::: 331
#pragma line 92 "C:/Xilinx/Vivado_HLS/2014.4/win32/tools/clang/bin/../lib/clang/3.1/../../../include\\math.h" 3 ::: 338
#pragma line 133 "C:/Xilinx/Vivado_HLS/2014.4/win32/tools/clang/bin/../lib/clang/3.1/../../../include\\math.h" 3 ::: 349
#pragma line 195 "C:/Xilinx/Vivado_HLS/2014.4/win32/tools/clang/bin/../lib/clang/3.1/../../../include\\math.h" 3 ::: 393
#pragma line 206 "C:/Xilinx/Vivado_HLS/2014.4/win32/tools/clang/bin/../lib/clang/3.1/../../../include\\math.h" 3 ::: 396
#pragma line 285 "C:/Xilinx/Vivado_HLS/2014.4/win32/tools/clang/bin/../lib/clang/3.1/../../../include\\math.h" 3 ::: 462
#pragma line 313 "C:/Xilinx/Vivado_HLS/2014.4/win32/tools/clang/bin/../lib/clang/3.1/../../../include\\math.h" 3 ::: 464
#pragma line 331 "C:/Xilinx/Vivado_HLS/2014.4/win32/tools/clang/bin/../lib/clang/3.1/../../../include\\math.h" 3 ::: 471
#pragma line 369 "C:/Xilinx/Vivado_HLS/2014.4/win32/tools/clang/bin/../lib/clang/3.1/../../../include\\math.h" 3 ::: 497
#pragma line 414 "C:/Xilinx/Vivado_HLS/2014.4/win32/tools/clang/bin/../lib/clang/3.1/../../../include\\math.h" 3 ::: 510
#pragma line 445 "C:/Xilinx/Vivado_HLS/2014.4/win32/tools/clang/bin/../lib/clang/3.1/../../../include\\math.h" 3 ::: 518
#pragma line 601 "C:/Xilinx/Vivado_HLS/2014.4/win32/tools/clang/bin/../lib/clang/3.1/../../../include\\math.h" 3 ::: 647
#pragma line 768 "C:/Xilinx/Vivado_HLS/2014.4/win32/tools/clang/bin/../lib/clang/3.1/../../../include\\math.h" 3 ::: 742
#pragma line 2 "coprocess/example/src/main.c" 2 ::: 840
#pragma line 1 "C:/Xilinx/Vivado_HLS/2014.4/win32/tools/clang/bin/../lib/clang/3.1/include\\stdint.h" 1 3 4 ::: 841
#pragma line 1 "C:/Xilinx/Vivado_HLS/2014.4/win32/tools/clang/bin/../lib/clang/3.1/../../../include\\stdint.h" 1 3 4 ::: 875
#pragma line 1 "C:/Xilinx/Vivado_HLS/2014.4/win32/tools/clang/bin/../lib/clang/3.1/include\\stddef.h" 1 3 4 ::: 900
#pragma line 56 "C:/Xilinx/Vivado_HLS/2014.4/win32/tools/clang/bin/../lib/clang/3.1/include\\stddef.h" 3 4 ::: 941
#pragma line 25 "C:/Xilinx/Vivado_HLS/2014.4/win32/tools/clang/bin/../lib/clang/3.1/../../../include\\stdint.h" 2 3 4 ::: 948
#pragma line 75 "C:/Xilinx/Vivado_HLS/2014.4/win32/tools/clang/bin/../lib/clang/3.1/../../../include\\stdint.h" 3 4 ::: 991
#pragma line 102 "C:/Xilinx/Vivado_HLS/2014.4/win32/tools/clang/bin/../lib/clang/3.1/../../../include\\stdint.h" 3 4 ::: 1004
#pragma line 118 "C:/Xilinx/Vivado_HLS/2014.4/win32/tools/clang/bin/../lib/clang/3.1/../../../include\\stdint.h" 3 4 ::: 1006
#pragma line 134 "C:/Xilinx/Vivado_HLS/2014.4/win32/tools/clang/bin/../lib/clang/3.1/../../../include\\stdint.h" 3 4 ::: 1008
#pragma line 146 "C:/Xilinx/Vivado_HLS/2014.4/win32/tools/clang/bin/../lib/clang/3.1/../../../include\\stdint.h" 3 4 ::: 1011
#pragma line 165 "C:/Xilinx/Vivado_HLS/2014.4/win32/tools/clang/bin/../lib/clang/3.1/../../../include\\stdint.h" 3 4 ::: 1018
#pragma line 200 "C:/Xilinx/Vivado_HLS/2014.4/win32/tools/clang/bin/../lib/clang/3.1/../../../include\\stdint.h" 3 4 ::: 1043
#pragma line 33 "C:/Xilinx/Vivado_HLS/2014.4/win32/tools/clang/bin/../lib/clang/3.1/include\\stdint.h" 2 3 4 ::: 1045
#pragma line 3 "coprocess/example/src/main.c" 2 ::: 1046
#pragma line 1 "coprocess/example/src/xilly_debug.h" 1 ::: 1047
#pragma line 4 "coprocess/example/src/main.c" 2 ::: 1056
