#pragma line 1 "coprocess/example/src/main.c" ::: -10
#pragma line 1 "coprocess/example/src/main.c" 1 ::: -9
#pragma line 1 "<built-in>" 1 ::: -8
#pragma line 1 "<built-in>" 3 ::: -7
#pragma line 148 "<built-in>" 3 ::: -6
#pragma line 1 "<command line>" 1 ::: -5
#pragma line 1 "C:/Xilinx/Vivado_HLS/2014.4/common/technology/autopilot\\etc/autopilot_ssdm_op.h" 1 ::: 3
#pragma line 278 "C:/Xilinx/Vivado_HLS/2014.4/common/technology/autopilot\\etc/autopilot_ssdm_op.h" ::: 56
#pragma line 9 "<command line>" 2 ::: 182
#pragma line 1 "<built-in>" 2 ::: 183
#pragma line 1 "coprocess/example/src/main.c" 2 ::: 184
#pragma line 1 "C:/Xilinx/Vivado_HLS/2014.4/win32/tools/clang/bin/../lib/clang/3.1/include\\stdint.h" 1 3 4 ::: 187
#pragma line 1 "C:/Xilinx/Vivado_HLS/2014.4/win32/tools/clang/bin/../lib/clang/3.1/../../../include\\stdint.h" 1 3 4 ::: 221
#pragma line 1 "C:/Xilinx/Vivado_HLS/2014.4/win32/tools/clang/bin/../lib/clang/3.1/include\\stddef.h" 1 3 4 ::: 246
#pragma line 56 "C:/Xilinx/Vivado_HLS/2014.4/win32/tools/clang/bin/../lib/clang/3.1/include\\stddef.h" 3 4 ::: 287
#pragma line 25 "C:/Xilinx/Vivado_HLS/2014.4/win32/tools/clang/bin/../lib/clang/3.1/../../../include\\stdint.h" 2 3 4 ::: 294
#pragma line 75 "C:/Xilinx/Vivado_HLS/2014.4/win32/tools/clang/bin/../lib/clang/3.1/../../../include\\stdint.h" 3 4 ::: 337
#pragma line 102 "C:/Xilinx/Vivado_HLS/2014.4/win32/tools/clang/bin/../lib/clang/3.1/../../../include\\stdint.h" 3 4 ::: 350
#pragma line 118 "C:/Xilinx/Vivado_HLS/2014.4/win32/tools/clang/bin/../lib/clang/3.1/../../../include\\stdint.h" 3 4 ::: 352
#pragma line 134 "C:/Xilinx/Vivado_HLS/2014.4/win32/tools/clang/bin/../lib/clang/3.1/../../../include\\stdint.h" 3 4 ::: 354
#pragma line 146 "C:/Xilinx/Vivado_HLS/2014.4/win32/tools/clang/bin/../lib/clang/3.1/../../../include\\stdint.h" 3 4 ::: 357
#pragma line 165 "C:/Xilinx/Vivado_HLS/2014.4/win32/tools/clang/bin/../lib/clang/3.1/../../../include\\stdint.h" 3 4 ::: 364
#pragma line 200 "C:/Xilinx/Vivado_HLS/2014.4/win32/tools/clang/bin/../lib/clang/3.1/../../../include\\stdint.h" 3 4 ::: 389
#pragma line 33 "C:/Xilinx/Vivado_HLS/2014.4/win32/tools/clang/bin/../lib/clang/3.1/include\\stdint.h" 2 3 4 ::: 391
#pragma line 3 "coprocess/example/src/main.c" 2 ::: 392
#pragma line 1 "coprocess/example/src/xilly_debug.h" 1 ::: 393
#pragma line 4 "coprocess/example/src/main.c" 2 ::: 402
