#pragma line 1 "coprocess/example/src/xilly_debug.c" ::: 0
#pragma line 1 "coprocess/example/src/xilly_debug.c" 1 ::: 1
#pragma line 1 "<built-in>" 1 ::: 2
#pragma line 1 "<built-in>" 3 ::: 3
#pragma line 148 "<built-in>" 3 ::: 4
#pragma line 1 "<command line>" 1 ::: 5
#pragma line 1 "C:/Xilinx/Vivado_HLS/2014.4/common/technology/autopilot\\etc/autopilot_ssdm_op.h" 1 ::: 13
#pragma line 278 "C:/Xilinx/Vivado_HLS/2014.4/common/technology/autopilot\\etc/autopilot_ssdm_op.h" ::: 66
#pragma line 9 "<command line>" 2 ::: 192
#pragma line 1 "<built-in>" 2 ::: 193
#pragma line 1 "coprocess/example/src/xilly_debug.c" 2 ::: 194
#pragma line 1 "coprocess/example/src/xilly_debug.h" 1 ::: 195
#pragma line 1 "C:/Xilinx/Vivado_HLS/2014.4/win32/tools/clang/bin/../lib/clang/3.1/include\\stdint.h" 1 3 4 ::: 199
#pragma line 1 "C:/Xilinx/Vivado_HLS/2014.4/win32/tools/clang/bin/../lib/clang/3.1/../../../include\\stdint.h" 1 3 4 ::: 233
#pragma line 1 "C:/Xilinx/Vivado_HLS/2014.4/win32/tools/clang/bin/../lib/clang/3.1/include\\stddef.h" 1 3 4 ::: 258
#pragma line 56 "C:/Xilinx/Vivado_HLS/2014.4/win32/tools/clang/bin/../lib/clang/3.1/include\\stddef.h" 3 4 ::: 299
#pragma line 25 "C:/Xilinx/Vivado_HLS/2014.4/win32/tools/clang/bin/../lib/clang/3.1/../../../include\\stdint.h" 2 3 4 ::: 306
#pragma line 75 "C:/Xilinx/Vivado_HLS/2014.4/win32/tools/clang/bin/../lib/clang/3.1/../../../include\\stdint.h" 3 4 ::: 349
#pragma line 102 "C:/Xilinx/Vivado_HLS/2014.4/win32/tools/clang/bin/../lib/clang/3.1/../../../include\\stdint.h" 3 4 ::: 362
#pragma line 118 "C:/Xilinx/Vivado_HLS/2014.4/win32/tools/clang/bin/../lib/clang/3.1/../../../include\\stdint.h" 3 4 ::: 364
#pragma line 134 "C:/Xilinx/Vivado_HLS/2014.4/win32/tools/clang/bin/../lib/clang/3.1/../../../include\\stdint.h" 3 4 ::: 366
#pragma line 146 "C:/Xilinx/Vivado_HLS/2014.4/win32/tools/clang/bin/../lib/clang/3.1/../../../include\\stdint.h" 3 4 ::: 369
#pragma line 165 "C:/Xilinx/Vivado_HLS/2014.4/win32/tools/clang/bin/../lib/clang/3.1/../../../include\\stdint.h" 3 4 ::: 376
#pragma line 200 "C:/Xilinx/Vivado_HLS/2014.4/win32/tools/clang/bin/../lib/clang/3.1/../../../include\\stdint.h" 3 4 ::: 401
#pragma line 33 "C:/Xilinx/Vivado_HLS/2014.4/win32/tools/clang/bin/../lib/clang/3.1/include\\stdint.h" 2 3 4 ::: 403
#pragma line 5 "coprocess/example/src/xilly_debug.h" 2 ::: 404
#pragma line 2 "coprocess/example/src/xilly_debug.c" 2 ::: 409
