-- ==============================================================
-- RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
-- Version: 2014.4
-- Copyright (C) 2014 Xilinx Inc. All rights reserved.
-- 
-- ===========================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity xillybus_wrapper_xilly_decprint is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    val_r : IN STD_LOGIC_VECTOR (7 downto 0);
    debug_ready : IN STD_LOGIC_VECTOR (7 downto 0);
    debug_out : OUT STD_LOGIC_VECTOR (7 downto 0);
    debug_out_ap_vld : OUT STD_LOGIC );
end;


architecture behav of xillybus_wrapper_xilly_decprint is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_st1_fsm_0 : STD_LOGIC_VECTOR (6 downto 0) := "0000001";
    constant ap_ST_st2_fsm_1 : STD_LOGIC_VECTOR (6 downto 0) := "0000010";
    constant ap_ST_st3_fsm_2 : STD_LOGIC_VECTOR (6 downto 0) := "0000100";
    constant ap_ST_st4_fsm_3 : STD_LOGIC_VECTOR (6 downto 0) := "0001000";
    constant ap_ST_st5_fsm_4 : STD_LOGIC_VECTOR (6 downto 0) := "0010000";
    constant ap_ST_st6_fsm_5 : STD_LOGIC_VECTOR (6 downto 0) := "0100000";
    constant ap_ST_st7_fsm_6 : STD_LOGIC_VECTOR (6 downto 0) := "1000000";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv32_2 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000010";
    constant ap_const_lv32_3 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000011";
    constant ap_const_lv32_4 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000100";
    constant ap_const_lv32_5 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000101";
    constant ap_const_lv32_9 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001001";
    constant ap_const_lv4_0 : STD_LOGIC_VECTOR (3 downto 0) := "0000";
    constant ap_const_lv8_0 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    constant ap_const_lv32_6 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000110";
    constant ap_const_lv32_A : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001010";
    constant ap_const_lv4_A : STD_LOGIC_VECTOR (3 downto 0) := "1010";
    constant ap_const_lv4_1 : STD_LOGIC_VECTOR (3 downto 0) := "0001";
    constant ap_const_lv8_1 : STD_LOGIC_VECTOR (7 downto 0) := "00000001";
    constant ap_const_lv8_30 : STD_LOGIC_VECTOR (7 downto 0) := "00110000";

    signal ap_CS_fsm : STD_LOGIC_VECTOR (6 downto 0) := "0000001";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_sig_cseq_ST_st1_fsm_0 : STD_LOGIC;
    signal ap_sig_bdd_25 : BOOLEAN;
    signal powers10_address0 : STD_LOGIC_VECTOR (3 downto 0);
    signal powers10_ce0 : STD_LOGIC;
    signal powers10_q0 : STD_LOGIC_VECTOR (27 downto 0);
    signal first_2_cast1_fu_142_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal first_2_cast1_reg_272 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_sig_cseq_ST_st2_fsm_1 : STD_LOGIC;
    signal ap_sig_bdd_48 : BOOLEAN;
    signal i_fu_153_p2 : STD_LOGIC_VECTOR (3 downto 0);
    signal i_reg_282 : STD_LOGIC_VECTOR (3 downto 0);
    signal exitcond_fu_147_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_4_fu_159_p1 : STD_LOGIC_VECTOR (4 downto 0);
    signal tmp_4_reg_292 : STD_LOGIC_VECTOR (4 downto 0);
    signal powers10_load_cast_fu_167_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal powers10_load_cast_reg_297 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_sig_cseq_ST_st3_fsm_2 : STD_LOGIC;
    signal ap_sig_bdd_69 : BOOLEAN;
    signal x_1_fu_179_p2 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_sig_cseq_ST_st4_fsm_3 : STD_LOGIC;
    signal ap_sig_bdd_78 : BOOLEAN;
    signal first_1_fu_219_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_fu_174_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_sig_cseq_ST_st5_fsm_4 : STD_LOGIC;
    signal ap_sig_bdd_93 : BOOLEAN;
    signal p_rec_i_fu_240_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal p_rec_i_reg_321 : STD_LOGIC_VECTOR (31 downto 0);
    signal out_q0 : STD_LOGIC_VECTOR (7 downto 0);
    signal out_load_reg_326 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_sig_cseq_ST_st6_fsm_5 : STD_LOGIC;
    signal ap_sig_bdd_104 : BOOLEAN;
    signal out_address0 : STD_LOGIC_VECTOR (3 downto 0);
    signal out_ce0 : STD_LOGIC;
    signal out_we0 : STD_LOGIC;
    signal out_d0 : STD_LOGIC_VECTOR (7 downto 0);
    signal first_reg_87 : STD_LOGIC_VECTOR (31 downto 0);
    signal first_2_reg_99 : STD_LOGIC_VECTOR (3 downto 0);
    signal x_reg_110 : STD_LOGIC_VECTOR (7 downto 0);
    signal p_0_rec_i_reg_121 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_sig_cseq_ST_st7_fsm_6 : STD_LOGIC;
    signal ap_sig_bdd_135 : BOOLEAN;
    signal tmp_9_fu_256_p1 : STD_LOGIC_VECTOR (0 downto 0);
    signal sum_i_cast_fu_235_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal v_fu_34 : STD_LOGIC_VECTOR (31 downto 0);
    signal v_1_fu_133_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal v_2_fu_185_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_6_fu_195_p2 : STD_LOGIC_VECTOR (7 downto 0);
    signal powers10_load_cast2_fu_163_p1 : STD_LOGIC_VECTOR (29 downto 0);
    signal tmp_7_fu_202_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_8_fu_208_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_cond_fu_213_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_5_fu_226_p1 : STD_LOGIC_VECTOR (4 downto 0);
    signal sum_i_fu_230_p2 : STD_LOGIC_VECTOR (4 downto 0);
    signal tmp_i_fu_246_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_NS_fsm : STD_LOGIC_VECTOR (6 downto 0);

    component xillybus_wrapper_xilly_decprint_powers10 IS
    generic (
        DataWidth : INTEGER;
        AddressRange : INTEGER;
        AddressWidth : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        address0 : IN STD_LOGIC_VECTOR (3 downto 0);
        ce0 : IN STD_LOGIC;
        q0 : OUT STD_LOGIC_VECTOR (27 downto 0) );
    end component;


    component xillybus_wrapper_xilly_decprint_out IS
    generic (
        DataWidth : INTEGER;
        AddressRange : INTEGER;
        AddressWidth : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        address0 : IN STD_LOGIC_VECTOR (3 downto 0);
        ce0 : IN STD_LOGIC;
        we0 : IN STD_LOGIC;
        d0 : IN STD_LOGIC_VECTOR (7 downto 0);
        q0 : OUT STD_LOGIC_VECTOR (7 downto 0) );
    end component;



begin
    powers10_U : component xillybus_wrapper_xilly_decprint_powers10
    generic map (
        DataWidth => 28,
        AddressRange => 10,
        AddressWidth => 4)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        address0 => powers10_address0,
        ce0 => powers10_ce0,
        q0 => powers10_q0);

    out_U : component xillybus_wrapper_xilly_decprint_out
    generic map (
        DataWidth => 8,
        AddressRange => 11,
        AddressWidth => 4)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        address0 => out_address0,
        ce0 => out_ce0,
        we0 => out_we0,
        d0 => out_d0,
        q0 => out_q0);





    -- the current state (ap_CS_fsm) of the state machine. --
    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_st1_fsm_0;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    -- first_2_reg_99 assign process. --
    first_2_reg_99_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_sig_cseq_ST_st4_fsm_3) and not((ap_const_lv1_0 = tmp_fu_174_p2)))) then 
                first_2_reg_99 <= i_reg_282;
            elsif (((ap_const_logic_1 = ap_sig_cseq_ST_st1_fsm_0) and not((ap_start = ap_const_logic_0)))) then 
                first_2_reg_99 <= ap_const_lv4_0;
            end if; 
        end if;
    end process;

    -- first_reg_87 assign process. --
    first_reg_87_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_sig_cseq_ST_st4_fsm_3) and not((ap_const_lv1_0 = tmp_fu_174_p2)))) then 
                first_reg_87 <= first_1_fu_219_p3;
            elsif (((ap_const_logic_1 = ap_sig_cseq_ST_st1_fsm_0) and not((ap_start = ap_const_logic_0)))) then 
                first_reg_87 <= ap_const_lv32_9;
            end if; 
        end if;
    end process;

    -- p_0_rec_i_reg_121 assign process. --
    p_0_rec_i_reg_121_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_sig_cseq_ST_st7_fsm_6) and not((ap_const_lv1_0 = tmp_9_fu_256_p1)))) then 
                p_0_rec_i_reg_121 <= p_rec_i_reg_321;
            elsif (((ap_const_logic_1 = ap_sig_cseq_ST_st2_fsm_1) and not((exitcond_fu_147_p2 = ap_const_lv1_0)))) then 
                p_0_rec_i_reg_121 <= ap_const_lv32_0;
            end if; 
        end if;
    end process;

    -- v_fu_34 assign process. --
    v_fu_34_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_sig_cseq_ST_st4_fsm_3) and (ap_const_lv1_0 = tmp_fu_174_p2))) then 
                v_fu_34 <= v_2_fu_185_p2;
            elsif (((ap_const_logic_1 = ap_sig_cseq_ST_st1_fsm_0) and not((ap_start = ap_const_logic_0)))) then 
                v_fu_34 <= v_1_fu_133_p1;
            end if; 
        end if;
    end process;

    -- x_reg_110 assign process. --
    x_reg_110_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_sig_cseq_ST_st3_fsm_2)) then 
                x_reg_110 <= ap_const_lv8_0;
            elsif (((ap_const_logic_1 = ap_sig_cseq_ST_st4_fsm_3) and (ap_const_lv1_0 = tmp_fu_174_p2))) then 
                x_reg_110 <= x_1_fu_179_p2;
            end if; 
        end if;
    end process;

    -- assign process. --
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_sig_cseq_ST_st2_fsm_1)) then
                first_2_cast1_reg_272(0) <= first_2_cast1_fu_142_p1(0);
    first_2_cast1_reg_272(1) <= first_2_cast1_fu_142_p1(1);
    first_2_cast1_reg_272(2) <= first_2_cast1_fu_142_p1(2);
    first_2_cast1_reg_272(3) <= first_2_cast1_fu_142_p1(3);
                i_reg_282 <= i_fu_153_p2;
            end if;
        end if;
    end process;

    -- assign process. --
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_sig_cseq_ST_st6_fsm_5)) then
                out_load_reg_326 <= out_q0;
            end if;
        end if;
    end process;

    -- assign process. --
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_sig_cseq_ST_st5_fsm_4)) then
                p_rec_i_reg_321 <= p_rec_i_fu_240_p2;
            end if;
        end if;
    end process;

    -- assign process. --
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_sig_cseq_ST_st3_fsm_2)) then
                powers10_load_cast_reg_297(0) <= powers10_load_cast_fu_167_p1(0);
    powers10_load_cast_reg_297(1) <= powers10_load_cast_fu_167_p1(1);
    powers10_load_cast_reg_297(2) <= powers10_load_cast_fu_167_p1(2);
    powers10_load_cast_reg_297(3) <= powers10_load_cast_fu_167_p1(3);
    powers10_load_cast_reg_297(4) <= powers10_load_cast_fu_167_p1(4);
    powers10_load_cast_reg_297(5) <= powers10_load_cast_fu_167_p1(5);
    powers10_load_cast_reg_297(6) <= powers10_load_cast_fu_167_p1(6);
    powers10_load_cast_reg_297(7) <= powers10_load_cast_fu_167_p1(7);
    powers10_load_cast_reg_297(8) <= powers10_load_cast_fu_167_p1(8);
    powers10_load_cast_reg_297(9) <= powers10_load_cast_fu_167_p1(9);
    powers10_load_cast_reg_297(10) <= powers10_load_cast_fu_167_p1(10);
    powers10_load_cast_reg_297(11) <= powers10_load_cast_fu_167_p1(11);
    powers10_load_cast_reg_297(12) <= powers10_load_cast_fu_167_p1(12);
    powers10_load_cast_reg_297(13) <= powers10_load_cast_fu_167_p1(13);
    powers10_load_cast_reg_297(14) <= powers10_load_cast_fu_167_p1(14);
    powers10_load_cast_reg_297(15) <= powers10_load_cast_fu_167_p1(15);
    powers10_load_cast_reg_297(16) <= powers10_load_cast_fu_167_p1(16);
    powers10_load_cast_reg_297(17) <= powers10_load_cast_fu_167_p1(17);
    powers10_load_cast_reg_297(18) <= powers10_load_cast_fu_167_p1(18);
    powers10_load_cast_reg_297(19) <= powers10_load_cast_fu_167_p1(19);
    powers10_load_cast_reg_297(20) <= powers10_load_cast_fu_167_p1(20);
    powers10_load_cast_reg_297(21) <= powers10_load_cast_fu_167_p1(21);
    powers10_load_cast_reg_297(22) <= powers10_load_cast_fu_167_p1(22);
    powers10_load_cast_reg_297(23) <= powers10_load_cast_fu_167_p1(23);
    powers10_load_cast_reg_297(24) <= powers10_load_cast_fu_167_p1(24);
    powers10_load_cast_reg_297(25) <= powers10_load_cast_fu_167_p1(25);
    powers10_load_cast_reg_297(26) <= powers10_load_cast_fu_167_p1(26);
    powers10_load_cast_reg_297(27) <= powers10_load_cast_fu_167_p1(27);
    powers10_load_cast_reg_297(28) <= powers10_load_cast_fu_167_p1(28);
    powers10_load_cast_reg_297(29) <= powers10_load_cast_fu_167_p1(29);
            end if;
        end if;
    end process;

    -- assign process. --
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_sig_cseq_ST_st2_fsm_1) and not((exitcond_fu_147_p2 = ap_const_lv1_0)))) then
                tmp_4_reg_292 <= tmp_4_fu_159_p1;
            end if;
        end if;
    end process;
    first_2_cast1_reg_272(31 downto 4) <= "0000000000000000000000000000";
    powers10_load_cast_reg_297(31 downto 30) <= "00";

    -- the next state (ap_NS_fsm) of the state machine. --
    ap_NS_fsm_assign_proc : process (ap_start, ap_CS_fsm, exitcond_fu_147_p2, tmp_fu_174_p2, tmp_9_fu_256_p1, tmp_i_fu_246_p2)
    begin
        case ap_CS_fsm is
            when ap_ST_st1_fsm_0 => 
                if (not((ap_start = ap_const_logic_0))) then
                    ap_NS_fsm <= ap_ST_st2_fsm_1;
                else
                    ap_NS_fsm <= ap_ST_st1_fsm_0;
                end if;
            when ap_ST_st2_fsm_1 => 
                if (not((exitcond_fu_147_p2 = ap_const_lv1_0))) then
                    ap_NS_fsm <= ap_ST_st5_fsm_4;
                else
                    ap_NS_fsm <= ap_ST_st3_fsm_2;
                end if;
            when ap_ST_st3_fsm_2 => 
                ap_NS_fsm <= ap_ST_st4_fsm_3;
            when ap_ST_st4_fsm_3 => 
                if (not((ap_const_lv1_0 = tmp_fu_174_p2))) then
                    ap_NS_fsm <= ap_ST_st2_fsm_1;
                else
                    ap_NS_fsm <= ap_ST_st4_fsm_3;
                end if;
            when ap_ST_st5_fsm_4 => 
                ap_NS_fsm <= ap_ST_st6_fsm_5;
            when ap_ST_st6_fsm_5 => 
                if (not((ap_const_lv1_0 = tmp_i_fu_246_p2))) then
                    ap_NS_fsm <= ap_ST_st1_fsm_0;
                else
                    ap_NS_fsm <= ap_ST_st7_fsm_6;
                end if;
            when ap_ST_st7_fsm_6 => 
                if (not((ap_const_lv1_0 = tmp_9_fu_256_p1))) then
                    ap_NS_fsm <= ap_ST_st5_fsm_4;
                else
                    ap_NS_fsm <= ap_ST_st7_fsm_6;
                end if;
            when others =>  
                ap_NS_fsm <= "XXXXXXX";
        end case;
    end process;

    -- ap_done assign process. --
    ap_done_assign_proc : process(ap_start, ap_sig_cseq_ST_st1_fsm_0, ap_sig_cseq_ST_st6_fsm_5, tmp_i_fu_246_p2)
    begin
        if (((not((ap_const_logic_1 = ap_start)) and (ap_const_logic_1 = ap_sig_cseq_ST_st1_fsm_0)) or ((ap_const_logic_1 = ap_sig_cseq_ST_st6_fsm_5) and not((ap_const_lv1_0 = tmp_i_fu_246_p2))))) then 
            ap_done <= ap_const_logic_1;
        else 
            ap_done <= ap_const_logic_0;
        end if; 
    end process;


    -- ap_idle assign process. --
    ap_idle_assign_proc : process(ap_start, ap_sig_cseq_ST_st1_fsm_0)
    begin
        if ((not((ap_const_logic_1 = ap_start)) and (ap_const_logic_1 = ap_sig_cseq_ST_st1_fsm_0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    -- ap_ready assign process. --
    ap_ready_assign_proc : process(ap_sig_cseq_ST_st6_fsm_5, tmp_i_fu_246_p2)
    begin
        if (((ap_const_logic_1 = ap_sig_cseq_ST_st6_fsm_5) and not((ap_const_lv1_0 = tmp_i_fu_246_p2)))) then 
            ap_ready <= ap_const_logic_1;
        else 
            ap_ready <= ap_const_logic_0;
        end if; 
    end process;


    -- ap_sig_bdd_104 assign process. --
    ap_sig_bdd_104_assign_proc : process(ap_CS_fsm)
    begin
                ap_sig_bdd_104 <= (ap_const_lv1_1 = ap_CS_fsm(5 downto 5));
    end process;


    -- ap_sig_bdd_135 assign process. --
    ap_sig_bdd_135_assign_proc : process(ap_CS_fsm)
    begin
                ap_sig_bdd_135 <= (ap_const_lv1_1 = ap_CS_fsm(6 downto 6));
    end process;


    -- ap_sig_bdd_25 assign process. --
    ap_sig_bdd_25_assign_proc : process(ap_CS_fsm)
    begin
                ap_sig_bdd_25 <= (ap_CS_fsm(0 downto 0) = ap_const_lv1_1);
    end process;


    -- ap_sig_bdd_48 assign process. --
    ap_sig_bdd_48_assign_proc : process(ap_CS_fsm)
    begin
                ap_sig_bdd_48 <= (ap_const_lv1_1 = ap_CS_fsm(1 downto 1));
    end process;


    -- ap_sig_bdd_69 assign process. --
    ap_sig_bdd_69_assign_proc : process(ap_CS_fsm)
    begin
                ap_sig_bdd_69 <= (ap_const_lv1_1 = ap_CS_fsm(2 downto 2));
    end process;


    -- ap_sig_bdd_78 assign process. --
    ap_sig_bdd_78_assign_proc : process(ap_CS_fsm)
    begin
                ap_sig_bdd_78 <= (ap_const_lv1_1 = ap_CS_fsm(3 downto 3));
    end process;


    -- ap_sig_bdd_93 assign process. --
    ap_sig_bdd_93_assign_proc : process(ap_CS_fsm)
    begin
                ap_sig_bdd_93 <= (ap_const_lv1_1 = ap_CS_fsm(4 downto 4));
    end process;


    -- ap_sig_cseq_ST_st1_fsm_0 assign process. --
    ap_sig_cseq_ST_st1_fsm_0_assign_proc : process(ap_sig_bdd_25)
    begin
        if (ap_sig_bdd_25) then 
            ap_sig_cseq_ST_st1_fsm_0 <= ap_const_logic_1;
        else 
            ap_sig_cseq_ST_st1_fsm_0 <= ap_const_logic_0;
        end if; 
    end process;


    -- ap_sig_cseq_ST_st2_fsm_1 assign process. --
    ap_sig_cseq_ST_st2_fsm_1_assign_proc : process(ap_sig_bdd_48)
    begin
        if (ap_sig_bdd_48) then 
            ap_sig_cseq_ST_st2_fsm_1 <= ap_const_logic_1;
        else 
            ap_sig_cseq_ST_st2_fsm_1 <= ap_const_logic_0;
        end if; 
    end process;


    -- ap_sig_cseq_ST_st3_fsm_2 assign process. --
    ap_sig_cseq_ST_st3_fsm_2_assign_proc : process(ap_sig_bdd_69)
    begin
        if (ap_sig_bdd_69) then 
            ap_sig_cseq_ST_st3_fsm_2 <= ap_const_logic_1;
        else 
            ap_sig_cseq_ST_st3_fsm_2 <= ap_const_logic_0;
        end if; 
    end process;


    -- ap_sig_cseq_ST_st4_fsm_3 assign process. --
    ap_sig_cseq_ST_st4_fsm_3_assign_proc : process(ap_sig_bdd_78)
    begin
        if (ap_sig_bdd_78) then 
            ap_sig_cseq_ST_st4_fsm_3 <= ap_const_logic_1;
        else 
            ap_sig_cseq_ST_st4_fsm_3 <= ap_const_logic_0;
        end if; 
    end process;


    -- ap_sig_cseq_ST_st5_fsm_4 assign process. --
    ap_sig_cseq_ST_st5_fsm_4_assign_proc : process(ap_sig_bdd_93)
    begin
        if (ap_sig_bdd_93) then 
            ap_sig_cseq_ST_st5_fsm_4 <= ap_const_logic_1;
        else 
            ap_sig_cseq_ST_st5_fsm_4 <= ap_const_logic_0;
        end if; 
    end process;


    -- ap_sig_cseq_ST_st6_fsm_5 assign process. --
    ap_sig_cseq_ST_st6_fsm_5_assign_proc : process(ap_sig_bdd_104)
    begin
        if (ap_sig_bdd_104) then 
            ap_sig_cseq_ST_st6_fsm_5 <= ap_const_logic_1;
        else 
            ap_sig_cseq_ST_st6_fsm_5 <= ap_const_logic_0;
        end if; 
    end process;


    -- ap_sig_cseq_ST_st7_fsm_6 assign process. --
    ap_sig_cseq_ST_st7_fsm_6_assign_proc : process(ap_sig_bdd_135)
    begin
        if (ap_sig_bdd_135) then 
            ap_sig_cseq_ST_st7_fsm_6 <= ap_const_logic_1;
        else 
            ap_sig_cseq_ST_st7_fsm_6 <= ap_const_logic_0;
        end if; 
    end process;

    debug_out <= out_load_reg_326;

    -- debug_out_ap_vld assign process. --
    debug_out_ap_vld_assign_proc : process(ap_sig_cseq_ST_st7_fsm_6, tmp_9_fu_256_p1)
    begin
        if (((ap_const_logic_1 = ap_sig_cseq_ST_st7_fsm_6) and not((ap_const_lv1_0 = tmp_9_fu_256_p1)))) then 
            debug_out_ap_vld <= ap_const_logic_1;
        else 
            debug_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    exitcond_fu_147_p2 <= "1" when (first_2_reg_99 = ap_const_lv4_A) else "0";
    first_1_fu_219_p3 <= 
        first_2_cast1_reg_272 when (or_cond_fu_213_p2(0) = '1') else 
        first_reg_87;
    first_2_cast1_fu_142_p1 <= std_logic_vector(resize(unsigned(first_2_reg_99),32));
    i_fu_153_p2 <= std_logic_vector(unsigned(first_2_reg_99) + unsigned(ap_const_lv4_1));
    or_cond_fu_213_p2 <= (tmp_7_fu_202_p2 and tmp_8_fu_208_p2);

    -- out_address0 assign process. --
    out_address0_assign_proc : process(first_2_cast1_reg_272, ap_sig_cseq_ST_st2_fsm_1, ap_sig_cseq_ST_st4_fsm_3, ap_sig_cseq_ST_st5_fsm_4, sum_i_cast_fu_235_p1)
    begin
        if ((ap_const_logic_1 = ap_sig_cseq_ST_st4_fsm_3)) then 
            out_address0 <= first_2_cast1_reg_272(4 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_sig_cseq_ST_st2_fsm_1)) then 
            out_address0 <= ap_const_lv32_A(4 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_sig_cseq_ST_st5_fsm_4)) then 
            out_address0 <= sum_i_cast_fu_235_p1(4 - 1 downto 0);
        else 
            out_address0 <= "XXXX";
        end if; 
    end process;


    -- out_ce0 assign process. --
    out_ce0_assign_proc : process(ap_sig_cseq_ST_st2_fsm_1, ap_sig_cseq_ST_st4_fsm_3, ap_sig_cseq_ST_st5_fsm_4)
    begin
        if (((ap_const_logic_1 = ap_sig_cseq_ST_st2_fsm_1) or (ap_const_logic_1 = ap_sig_cseq_ST_st4_fsm_3) or (ap_const_logic_1 = ap_sig_cseq_ST_st5_fsm_4))) then 
            out_ce0 <= ap_const_logic_1;
        else 
            out_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    -- out_d0 assign process. --
    out_d0_assign_proc : process(ap_sig_cseq_ST_st2_fsm_1, ap_sig_cseq_ST_st4_fsm_3, tmp_6_fu_195_p2)
    begin
        if ((ap_const_logic_1 = ap_sig_cseq_ST_st4_fsm_3)) then 
            out_d0 <= tmp_6_fu_195_p2;
        elsif ((ap_const_logic_1 = ap_sig_cseq_ST_st2_fsm_1)) then 
            out_d0 <= ap_const_lv8_0;
        else 
            out_d0 <= "XXXXXXXX";
        end if; 
    end process;


    -- out_we0 assign process. --
    out_we0_assign_proc : process(ap_sig_cseq_ST_st2_fsm_1, exitcond_fu_147_p2, ap_sig_cseq_ST_st4_fsm_3, tmp_fu_174_p2)
    begin
        if ((((ap_const_logic_1 = ap_sig_cseq_ST_st2_fsm_1) and not((exitcond_fu_147_p2 = ap_const_lv1_0))) or ((ap_const_logic_1 = ap_sig_cseq_ST_st4_fsm_3) and not((ap_const_lv1_0 = tmp_fu_174_p2))))) then 
            out_we0 <= ap_const_logic_1;
        else 
            out_we0 <= ap_const_logic_0;
        end if; 
    end process;

    p_rec_i_fu_240_p2 <= std_logic_vector(unsigned(p_0_rec_i_reg_121) + unsigned(ap_const_lv32_1));
    powers10_address0 <= first_2_cast1_fu_142_p1(4 - 1 downto 0);

    -- powers10_ce0 assign process. --
    powers10_ce0_assign_proc : process(ap_sig_cseq_ST_st2_fsm_1)
    begin
        if ((ap_const_logic_1 = ap_sig_cseq_ST_st2_fsm_1)) then 
            powers10_ce0 <= ap_const_logic_1;
        else 
            powers10_ce0 <= ap_const_logic_0;
        end if; 
    end process;

        powers10_load_cast2_fu_163_p1 <= std_logic_vector(resize(signed(powers10_q0),30));

    powers10_load_cast_fu_167_p1 <= std_logic_vector(resize(unsigned(powers10_load_cast2_fu_163_p1),32));
    sum_i_cast_fu_235_p1 <= std_logic_vector(resize(unsigned(sum_i_fu_230_p2),32));
    sum_i_fu_230_p2 <= std_logic_vector(unsigned(tmp_5_fu_226_p1) + unsigned(tmp_4_reg_292));
    tmp_4_fu_159_p1 <= first_reg_87(5 - 1 downto 0);
    tmp_5_fu_226_p1 <= p_0_rec_i_reg_121(5 - 1 downto 0);
    tmp_6_fu_195_p2 <= (x_reg_110 or ap_const_lv8_30);
    tmp_7_fu_202_p2 <= "0" when (x_reg_110 = ap_const_lv8_0) else "1";
    tmp_8_fu_208_p2 <= "1" when (signed(first_reg_87) > signed(first_2_cast1_reg_272)) else "0";
    tmp_9_fu_256_p1 <= debug_ready(1 - 1 downto 0);
    tmp_fu_174_p2 <= "1" when (unsigned(v_fu_34) < unsigned(powers10_load_cast_reg_297)) else "0";
    tmp_i_fu_246_p2 <= "1" when (out_q0 = ap_const_lv8_0) else "0";
    v_1_fu_133_p1 <= std_logic_vector(resize(unsigned(val_r),32));
    v_2_fu_185_p2 <= std_logic_vector(unsigned(v_fu_34) - unsigned(powers10_load_cast_reg_297));
    x_1_fu_179_p2 <= std_logic_vector(unsigned(x_reg_110) + unsigned(ap_const_lv8_1));
end behav;
